[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit MLX90614 Library@^2.1.0
    fastled/FastLED@^3.7.5
    blynkkk/Blynk@^2.0.0
    adafruit/Adafruit BusIO@^1.16.0