; PlatformIO Project Configuration File

[env:esp32doit-devkit-v1]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; Active core application build.
build_src_filter = +<main.cpp>

; Improve library dependency resolution through local libs.
lib_ldf_mode = deep+

lib_deps =
    bodmer/TFT_eSPI

build_flags =
    -I include
    -include include/Constants.h
