; PlatformIO Project Configuration File

[env:esp32doit-devkit-v1]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_port = COM3
upload_speed = 57600

; Build only main.cpp for the display branch
build_src_filter = +<main.cpp> -<sound.cpp> -<ledText.cpp>

lib_deps =
    bodmer/TFT_eSPI
    git@github.com:santiago-pelaez/esp-dsp.git#master

lib_ignore =
    FastLED
    Blynk
    BlynkNcpDriver
    BlynkManager

build_flags = 
    -I include
    -include include/User_Setup.h
